# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.3
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: bit@d13.co
author_name: Bit D13
contract_name: repro
preset_name: production
project_name: repro-numbers-contracts

