# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: bit@d13.co
author_name: Bit D13
cloud_provider: none
preset_name: production
project_name: repro-numbers-frontend

